

                 expression  ::=  arithmeticExpression

                               ;


       arithmeticExpression  ::=  addition 

                               |  subtraction 

                               ;


                   addition  ::=  expression "+" expression ;

                subtraction  ::=  expression "-" expression ;
