

                  statement  ::=  lessThan

                               |  greaterThan

                               |  lessThanOrEqualTo

                               |  greaterThanOrEqualTo

                               ;



                   lessThan  ::=  expression "<" expression ;

                greaterThan  ::=  expression ">" expression ;

          lessThanOrEqualTo  ::=  expression "<=" expression ;

       greaterThanOrEqualTo  ::=  expression ">=" expression ;
