

                       term  ::=  operation

                               |  operator

                               |  substring

                               |  stringLength

                               ;


                  operation  ::=  operator<NO_WHITESPACE>"(" term ")" ;


                   operator  ::=  "insert"<NO_WHITESPACE>"(" term "," term ")"

                               |  "delete"<NO_WHITESPACE>"(" term "," term ")" 

                               |  "empty"<NO_WHITESPACE>"("<NO_WHITESPACE>")"

                               ;


                  substring  ::=  name<NO_WHITESPACE>"[" "..." expression "]" 

                               |  name<NO_WHITESPACE>"[" expression "..." expression "]" 

                               |  name<NO_WHITESPACE>"[" expression "..."  "]" 

                               ;


               stringLength  ::=  "|" term "|" ;


