

                stringTerm  ::=  operation  

                              |  operator

                              ;

 

                 operation  ::=  operator<NO_WHITESPACE>"(" stringExpression ")" ;



                  operator  ::=  "insert"<NO_WHITESPACE>"(" naturalNumber "," stringExpression ")"

                              |  "delete"<NO_WHITESPACE>"(" naturalNumber "," naturalNumber ")" 

                              |  "empty"<NO_WHITESPACE>"("<NO_WHITESPACE>")"

                              ;
