

                       term  ::=  operation<NO_WHITESPACE>"(" term ")"

                               |  operation

                               ;


                  operation  ::=  "insert"<NO_WHITESPACE>"(" term "," term ")"

                               |  "delete"<NO_WHITESPACE>"(" term "," term ")" 

                               |  "empty"<NO_WHITESPACE>"("<NO_WHITESPACE>")"

                               ;
